---
include:
  - board: nice_nano//zmk
    shield: kyria_left
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
  - board: nice_nano//zmk
    shield: kyria_right
  - board: nice_nano//zmk
    shield: settings_reset
